name: Process New Album

on:
  workflow_dispatch:
    inputs:
      album_name:
        description: 'Name of the album'
        required: true
        type: string
      album_title:
        description: 'Title of the album'
        required: true
        type: string
      album_date:
        description: 'Date of the album (YYYY-MM-DD)'
        required: true
        type: string
      album_description:
        description: 'Description of the album'
        required: false
        type: string
        default: ''
      cover_image:
        description: 'Name of the cover image file (optional)'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  process_album:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: photography-automation
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow jsonschema
          
      - name: Create temporary directory for images
        run: |
          mkdir -p "/tmp/album_images/${{ github.event.inputs.album_name }}"
          echo "Created temporary directory for images"
          
      - name: Create album using existing script
        run: |
          cd photography/utils
          python create_album.py \
            --name "${{ github.event.inputs.album_name }}" \
            --title "${{ github.event.inputs.album_title }}" \
            --description "${{ github.event.inputs.album_description }}" \
            --date "${{ github.event.inputs.album_date }}" \
            --image-dir "/tmp/album_images/${{ github.event.inputs.album_name }}" \
            --cover-image "${{ github.event.inputs.cover_image }}"
          
      - name: Show album structure
        run: |
          echo "Created album structure:"
          ls -R photography/albums/${{ github.event.inputs.album_name }}
