name: Process New Album

on:
  workflow_dispatch:
    inputs:
      album_name:
        description: 'Name of the album'
        required: true
        type: string
      album_date:
        description: 'Date of the album (YYYY-MM-DD)'
        required: true
        type: string
      album_description:
        description: 'Description of the album'
        required: false
        type: string
        default: ''

permissions:
  contents: write
  actions: write

jobs:
  process_album:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: photography-automation
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow jsonschema
          
      - name: Setup album structure
        run: |
          echo "Processing album: ${{ github.event.inputs.album_name }}"
          echo "Date: ${{ github.event.inputs.album_date }}"
          echo "Description: ${{ github.event.inputs.album_description }}"
          
          # Create album directory structure
          mkdir -p "photography/albums/${{ github.event.inputs.album_name }}"
          mkdir -p "photography/albums/${{ github.event.inputs.album_name }}/original"
          mkdir -p "photography/albums/${{ github.event.inputs.album_name }}/processed"
          
          # Create album metadata
          cat > "photography/albums/${{ github.event.inputs.album_name }}/metadata.json" << EOF
          {
            "name": "${{ github.event.inputs.album_name }}",
            "date": "${{ github.event.inputs.album_date }}",
            "description": "${{ github.event.inputs.album_description }}",
            "created_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "status": "pending"
          }
          EOF
          
      - name: List created structure
        run: |
          echo "Created album structure:"
          ls -R photography/albums/${{ github.event.inputs.album_name }}
