name: iOS Album Processor

on:
  workflow_dispatch:
    inputs:
      album_name:
        description: 'Name of the album (URL-friendly)'
        required: true
        type: string
      album_title:
        description: 'Display title of the album'
        required: true
        type: string
      album_date:
        description: 'Date of the album (YYYY-MM-DD)'
        required: true
        type: string
      icloud_share_url:
        description: 'iCloud Shared Album URL'
        required: true
        type: string

permissions:
  contents: write

jobs:
  process_album:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feat/ios-album-automation
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow jsonschema requests beautifulsoup4

      - name: Create temporary directory for images
        run: |
          mkdir -p "/tmp/album_images/${{ github.event.inputs.album_name }}"
          echo "Created temporary directory: /tmp/album_images/${{ github.event.inputs.album_name }}"
      
      - name: Echo inputs (debug)
        run: |
          echo "Album Name: ${{ github.event.inputs.album_name }}"
          echo "Album Title: ${{ github.event.inputs.album_title }}"
          echo "Album Date: ${{ github.event.inputs.album_date }}"
          echo "iCloud URL: ${{ github.event.inputs.icloud_share_url }}"
